---
 - name: Install Apache and Upload my Web Page
   hosts: all
   become: yes

   vars:                                      #various for example
     source_file: ./MyWebSite/index.html
     destin_file:  /var/www/html

   tasks:                                     # these are commands what we want to do
   - name: Check and Print Linux versions
     debug: var=ansible_os_family

   - block:   ##### block for RedHat #####

      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest

      - name: Copy MyHomePage to Servers for RedHat
        copy: src={{ source_file }}  dest={{ destin_file }} mode=0555
        notify: Restart Apache RedHat

      - name: Start WebServer and make it enable for RedHat
        service: name=httpd state=started enabled=yes

      when: ansible_os_family == "RedHat"

    - block:  ##### block for Debian #####

      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: Copy MyHomePage to Servers for Debian
        copy: src={{ source_file }}  dest={{ destin_file }} mode=0555
        notify: Restart Apache                # command to restart server after previous command "Install"

      - name: Start WebServer and make it enable for Debian
        service: name=apache2 state=started enabled=yes

     when: ansible_os_family == "Debian"

   handlers:                              # need to restart server after installed
   - name: Restart Apache on RedHat
     service: name=httpd state=restarted

   - name: Restart Apache on Debian
     service: name=apache2 state=restarted
